twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - bootstrap_5_layout.html.twig
        # - autre_theme.html.twig
        # - dernier_theme.html.twig
    globals:
        categoryRepository: "@App\\Repository\\CategoryRepository"

when@test:
    twig:
        strict_variables: true

