twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - bootstrap_5_layout.html.twig
        # - autre_theme.html.twig
        # - dernier_theme.html.twig
    globals:  
    #? NB : globals fait que toute variable dans globals on peut y accéder dans tous nos fishier twig  
        categoryRepository: "@App\\Repository\\CategoryRepository"
        cartService: "@App\\Cart\\CartService" 

when@test:
    twig:
        strict_variables: true

